### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by aseques** [ArtyomYudin/AvayaCDRCollector#4]
hi @ArtyomYudin I am looking for an avaya collector and found about your code, by looking on the files it seems to me that it's launched with pm2 (at least it seems quite similar)? 
What is the file where to setup the mysql database connection? 

Regards and thanks for you effort

**Comment by ArtyomYudin** [comment]
create file .env.production

NET_SOCKET_PORT=9000
NET_SOCKET_ADDR=
DB_HOST=
DB_USER=
DB_PASSWORD=

**Comment by aseques** [comment]
Thanks, with that I could launch the code
